### ISSUE TITLE
while searching for words, clicking on a search result doesnt redirect to word

### ISSUE THREAD

**Issue by Emangi-FCMG** [bunny0310/VocabBoosterV3#19]

**Comment by bunny0310** [comment]
LOW priority

**Comment by bunny0310** [comment]
This bug has now been rendered moot. As per the suggestion from Erik, the search box now filters directly on the typed in phrase and updates the screen with the filtered words. The plans to have a modal search for words and also allow filtering on more properties than just the name of the word have been shelved for now.
