### ISSUE TITLE
Graph for Analytics

### ISSUE THREAD

**Issue by YamMangalili** [bunny0310/VocabBoosterV3#7]
As a user I want to be able to see what type of words/phrases(adjective, noun, metaphor,... etc) and how many of each type I have been learning throughout a span of a certain time.

**Comment by bunny0310** [comment]
Yam attempted this and researched different libraries that can be used to implement this feature. We eventually decided to go with Chart.js and its react version called react-chartjs-2 (or something along those lines). Ishaan implemented the feature.
